language: r
dist: focal

#r:
#  - release
#  - oldrel
#  - devel

services:
  - xvfb

before_install:
  - tlmgr option repository ctan
  - tlmgr update --self
  - tlmgr install hyphenat pgfplots textpos

addons:
  apt:
    packages:
      - tk-dev
      - bwidget
      - ghostscript
      - libnlopt-dev

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
