language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

services:
  - xvfb

before_install:
  - tlmgr install hyphenat pgfplots textpos

addons:
  apt:
    packages:
      - tk-dev
      - bwidget
      - ghostscript
      - libnlopt-dev

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
