language: r
sudo: false
cache: packages

#r:
#  - oldrel
#  - release
#  - devel

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - tlmgr install hyphenat pgfplots textpos

addons:
  apt:
    packages:
      - tk-dev
      - bwidget
